name: Deploy to HostData

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare Deployment Files
        run: |
          mkdir dist
          cp -r index.html css/ js/ img/ dist/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 82.25.62.13
          username: portofolio@fauzihabibi.my.id
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /domains/portofolio.fauzihabibi.my.id/public_html/
